### ISSUE TITLE
Metadata File

### ISSUE THREAD

**Issue by Tsaraswathi** [AU-DIS/BeCom#1]
Hi, 

I was going through your paper "GraB: Graph Benchmark for Heterogeneous Graph Clustering" for my work. The paper explained the dataset very well. It mentions that there are 22 clusters each pertaining to a movie genre. However, do you have any metadata file which talks about what the cluster names are( the data shows only numbers. So, was hoping to understand what cluster the number indicates) or node names and other stuff. Such information about the data is really helpful.

Hoping to hear back. Thanks!!

**Comment by TheSpeky** [comment]
Sorry for the late responds. 
It is now available in the dataset folder in genre_indicies.json, which maps the genres to their index representation.
